"""Core runtime type contracts for Agent Runtime Lab."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

ExecutionMode = Literal["react", "plan_execute"]
PlanStatus = Literal["pending", "in_progress", "completed", "failed", "skipped"]
SessionStatus = Literal["running", "completed", "failed", "stopped"]
ToolKind = Literal["local", "http", "mcp", "mock"]
BenchmarkCategory = Literal["tool", "rag", "constraint"]


def _utc_now() -> datetime:
    return datetime.now(tz=UTC)


def _new_id() -> str:
    return uuid4().hex


class BaseContract(BaseModel):
    """Shared model defaults for all runtime contracts."""

    model_config = ConfigDict(extra="forbid", validate_assignment=True)


class TaskSpec(BaseContract):
    """User task definition used by planner/runtime entrypoints."""

    task_id: str = Field(default_factory=_new_id)
    title: str
    objective: str
    input_payload: dict[str, Any] = Field(default_factory=dict)
    constraints: list[str] = Field(default_factory=list)
    context: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class PlanNode(BaseContract):
    """A single planned node generated by planner."""

    step_id: str = Field(default_factory=_new_id)
    title: str
    description: str
    status: PlanStatus = "pending"
    depends_on: list[str] = Field(default_factory=list)
    expected_output: str | None = None
    retries: int = Field(default=0, ge=0)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolSpec(BaseContract):
    """Tool registry metadata and invocation constraints."""

    name: str
    description: str
    kind: ToolKind = "local"
    input_schema: dict[str, Any] = Field(default_factory=dict)
    output_schema: dict[str, Any] = Field(default_factory=dict)
    timeout_ms: int = Field(default=4000, gt=0)
    retry: int = Field(default=0, ge=0)
    allow_network: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolCall(BaseContract):
    """Tool invocation request emitted by executor."""

    call_id: str = Field(default_factory=_new_id)
    tool_name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    requested_at: datetime = Field(default_factory=_utc_now)


class ToolResult(BaseContract):
    """Tool invocation output consumed by runtime/critic."""

    call_id: str
    tool_name: str
    success: bool
    output: Any = None
    error: str | None = None
    latency_ms: int | None = Field(default=None, ge=0)
    metadata: dict[str, Any] = Field(default_factory=dict)
    returned_at: datetime = Field(default_factory=_utc_now)


class ExecutionStep(BaseContract):
    """Single executor iteration record."""

    step_id: str = Field(default_factory=_new_id)
    plan_step_id: str | None = None
    thought_summary: str
    selected_tool: str | None = None
    tool_call: ToolCall | None = None
    tool_result: ToolResult | None = None
    observation: str | None = None
    state_update: str = ""
    success: bool = True
    latency_ms: int | None = Field(default=None, ge=0)
    token_estimate: int | None = Field(default=None, ge=0)
    metadata: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=_utc_now)


class TraceEvent(BaseContract):
    """Structured trace event persisted to JSONL/SQLite."""

    session_id: str
    step_id: str
    mode: ExecutionMode
    thought_summary: str
    selected_tool: str = "none"
    tool_input: dict[str, Any] | None = None
    tool_output: Any = None
    state_update: str
    latency_ms: int = Field(default=0, ge=0)
    token_estimate: int = Field(default=0, ge=0)
    timestamp: datetime = Field(default_factory=_utc_now)


class SessionState(BaseContract):
    """Mutable runtime state for a single task session."""

    session_id: str = Field(default_factory=_new_id)
    mode: ExecutionMode
    task: TaskSpec
    goal: str
    status: SessionStatus = "running"
    current_step: int = Field(default=0, ge=0)
    plan: list[PlanNode] = Field(default_factory=list)
    history: list[ExecutionStep] = Field(default_factory=list)
    tool_results: list[ToolResult] = Field(default_factory=list)
    interim_conclusions: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    error_log: list[str] = Field(default_factory=list)
    memory_summary: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)


class EvalRecord(BaseContract):
    """Per-case evaluation output used by benchmark runner."""

    case_id: str
    mode: ExecutionMode
    success: bool
    steps: int = Field(default=0, ge=0)
    latency_ms: int = Field(default=0, ge=0)
    tool_calls: int = Field(default=0, ge=0)
    tool_call_success: int = Field(default=0, ge=0)
    constraint_retained: bool = False
    score: float | None = None
    notes: str | None = None
    trace_file: str | None = None


class BenchmarkCase(BaseContract):
    """Benchmark dataset item contract."""

    case_id: str
    category: BenchmarkCategory
    prompt: str
    constraints: list[str] = Field(default_factory=list)
    context_docs: list[str] = Field(default_factory=list)
    expected_keywords: list[str] = Field(default_factory=list)
    forbidden_keywords: list[str] = Field(default_factory=list)
    expected_tool_calls: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


__all__ = [
    "BenchmarkCase",
    "BenchmarkCategory",
    "EvalRecord",
    "ExecutionMode",
    "ExecutionStep",
    "PlanNode",
    "PlanStatus",
    "SessionState",
    "SessionStatus",
    "TaskSpec",
    "ToolCall",
    "ToolKind",
    "ToolResult",
    "ToolSpec",
    "TraceEvent",
]
